Repository Icinga/icingadb, pull requests merged in 2019-12, with the labels that each got.

#77 XREAD from icinga:stats
  connection/redis.go
  ha/heartbeat.go
  ha/heartbeat_test.go
Labels: area/ha

#57 Add notification recipients
  configobject/objecttypes/notification/notificationrecipient/notificationrecipient.go
  etc/schema/mysql/mysql.schema.sql
  main.go
Labels: area/configsync, enhancement

#72 ConfigSync: Add worker debug logging
  configobject/configsync/configsync.go
Labels: area/configsync

#78 HA: Populate environment table
  ha/ha.go
  ha/ha_test.go
Labels: area/ha

#79 HA: Fix MySQL formatting
  ha/ha.go
  ha/ha_test.go
Labels: area/ha

#84 History: Add cancelled_by & removed_by to downtime & comment history
  configobject/history/history.go
  etc/schema/mysql/mysql.schema.sql
Labels: area/history

#82 Schema: include consistent IDs, start time and end time in flapping and acknowledgement history
  configobject/history/history.go
  etc/schema/mysql/mysql.schema.sql
  utils/convert.go
Labels: area/history

#88 Add to icingadb:overdue:* before updating database
  configobject/statesync/overdue.go
Labels: area/statesync

#92 HA: Write heartbeat in milliseconds
  ha/ha.go
  utils/convert.go
Labels: area/ha

#94 HA: Add missing milliseconds conversion
  ha/ha.go
Labels: area/ha

#95 Wait for a new heartbeat
  ha/heartbeat.go
Labels: area/ha

#96 HA: Add missing Icinga 2 status information to heartbeat/icingadb_instance
  etc/schema/mysql/mysql.schema.sql
  ha/ha.go
  ha/heartbeat.go
Labels: area/ha

#97 HA: Do not use seconds in responsibility check
  ha/ha.go
  ha/ha_test.go
Labels: area/ha, bug
