Repository Icinga/icingadb, pull requests merged in 2020-04, with the labels that each got.

#154 Update go mod
  go.mod
  go.sum
Labels: dependencies

#166 Correct typo in context image
  doc/images/about/icinga-db-in-icinga-context.png
Labels: area/documentation

#167 Schema: Change *command_argument.argument_order from tinyint to smallint
  etc/schema/mysql/mysql.schema.sql
Labels: area/connection, bug
