Repository Icinga/icingadb, pull requests merged in 2021-11, with the labels that each got.

#297 Sync customvar flat runtime updates
  cmd/icingadb/main.go
  pkg/common/sync_subject.go
  pkg/contracts/contracts.go
  pkg/icingadb/db.go
  pkg/icingadb/runtime_updates.go
  pkg/icingadb/sync.go
  pkg/icingadb/v1/customvar.go
  tests/object_sync_test.go
Labels: cla/signed

#392 Make {NotificationHistory,StateHistory,History*}#Id UUID -> SHA1
  cmd/icingadb/main.go
  pkg/icingadb/history/sync.go
  pkg/icingadb/v1/history/meta.go
  pkg/icingadb/v1/history/notification.go
  pkg/icingadb/v1/history/state.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: cla/signed

#393 Sync history independent of HA
  cmd/icingadb/main.go
Labels: cla/signed

#401 Fix flawed config keys and validation
  pkg/icingadb/db.go
  pkg/icingaredis/client.go
Labels: cla/signed

#391 Better handling of multiple environments
  cmd/icingadb/main.go
  pkg/contracts/contracts.go
  pkg/icingadb/db.go
  pkg/icingadb/ha.go
  pkg/icingadb/scoped_entity.go
  pkg/icingadb/sync.go
  pkg/icingadb/v1/environment.go
  pkg/icingadb/v1/v1.go
  pkg/icingaredis/heartbeat.go
  pkg/icingaredis/v1/icinga_status.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
  tests/environment_test.go
Labels: cla/signed

#396 Logging
  cmd/icingadb/main.go
  config.yml.example
  doc/03-Configuration.md
  internal/command/command.go
  pkg/com/counter.go
  pkg/config/database.go
  pkg/config/logging.go
  pkg/config/redis.go
  pkg/driver/driver.go
  pkg/icingadb/db.go
  pkg/icingadb/delta.go
  pkg/icingadb/delta_test.go
  pkg/icingadb/dump_signals.go
  pkg/icingadb/ha.go
  pkg/icingadb/history/sync.go
  pkg/icingadb/overdue/sync.go
  pkg/icingadb/runtime_updates.go
  pkg/icingadb/sync.go
  pkg/icingaredis/client.go
  pkg/icingaredis/heartbeat.go
  pkg/logging/logger.go
  pkg/logging/logging.go
  pkg/periodic/periodic.go
  pkg/retry/retry.go
Labels: cla/signed

#388 Replace Apache 2.0 licensed gopkg.in/yaml.v3 with MIT licensed github.com/goccy/go-yaml
  go.mod
  go.sum
  pkg/config/config.go
Labels: cla/signed

#379 GitHub actions: assert GPLv2 compatibility of all deps' licenses
  .github/workflows/compliance.yml
  .github/workflows/compliance/anonymize-license.pl
  .github/workflows/compliance/check-licenses.sh
  .github/workflows/compliance/ls-deps.pl
Labels: cla/signed

#385 Schema: Prefix command_id with command type (check, event, notification)
  cmd/icingadb/main.go
  pkg/icingadb/v1/command.go
  pkg/icingadb/v1/notification.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: area/schema, cla/signed

#407 Schema: Fix index typos + missing comment change
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: area/schema, cla/signed

#403 Add new mysql column `downtime.duration` & `service_state.host_id`
  pkg/icingadb/v1/downtime.go
  pkg/icingadb/v1/service.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: cla/signed

#394 RuntimeUpdates#Sync(): force FIFO for config updates
  cmd/icingadb/main.go
  pkg/com/bulker.go
  pkg/com/entity_bulker.go
  pkg/icingadb/runtime_updates.go
  tests/go.mod
  tests/go.sum
  tests/regression_394_test.go
Labels: cla/signed

#408 Fix broken retry mechanics
  pkg/retry/retry.go
Labels: cla/signed

#399 Integration tests for history sync in HA setups
  tests/go.mod
  tests/go.sum
  tests/history_test.go
  tests/history_test_zones.conf
Labels: area/history, cla/signed, area/tests

#411 Insert schema version last
  schema/mysql/schema.sql
Labels: cla/signed

#409 Improve example configuration, docs and config defaults
  README.md
  config.yml.example
  doc/02-Installation.md
  doc/03-Configuration.md
  doc/04-Upgrading.md
  pkg/config/config.go
  pkg/icingaredis/client.go
Labels: cla/signed

#410 Make NotificationRecipient struct readable
  pkg/icingadb/v1/notification.go
Labels: cla/signed

#412 Use own connections for heartbeat and HA
  cmd/icingadb/main.go
Labels: cla/signed

#397 Add more MySQL indexes
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: cla/signed

#313 Update authors and remove authors whose code is no longer in the repo
  .mailmap
  AUTHORS
Labels: needs-feedback, cla/signed

#404 Integration tests: Add notifications and improve user runtime updates
  tests/go.mod
  tests/go.sum
  tests/internal/utils/slice.go
  tests/internal/utils/slice_test.go
  tests/object_sync_test.conf
  tests/object_sync_test.go
Labels: cla/signed

#415 go.mod: remove redundant replacement
  go.mod
  go.sum
Labels: cla/signed
