Repository Icinga/icingadb, pull requests merged in 2021-02, with the labels that each got.

#255 ChunkRows(): ensure to never get an empty chunk
  connection/mysql_utils_test.go
Labels: enhancement

#232 HA: Prevent multiple instances from taking over at the same time
  configobject/configsync/configsync.go
  configobject/configsync/configsync_test.go
  configobject/configsync/ha.go
  configobject/configsync/ha_test.go
  connection/mysql.go
  connection/mysql_test.go
  ha/ha.go
  ha/ha_test.go
  ha/heartbeat.go
  ha/state.go
  main.go
Labels: area/ha, bug

#239 Make overdue sync HA-aware
  configobject/statesync/overdue.go
  configobject/statesync/statesync.go
  connection/redis.go
  main.go
Labels: area/ha, area/statesync, bug
