Repository Icinga/icingadb, pull requests merged in 2021-08, with the labels that each got.

#322 Icinga DB: introduce Checkable#last_comment_id
  pkg/icingadb/v1/state.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: area/schema

#326 Don't append(x,y) if x is not to be modified
  cmd/icingadb/main.go
Labels: bug

#333 Allow acknowledgement_history#{author,is_sticky,is_persistent} being NULL
  pkg/icingadb/v1/history/ack.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: bug, cla/signed

#341 Log MySQL driver errors at the debug level instead of discarding them
  pkg/driver/driver.go
Labels: cla/signed

#340 Also retry driver.ErrBadConn
  pkg/icingadb/db.go
Labels: cla/signed

#339 Enlarge {comment,downtime}#name 255 -> 548
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: cla/signed

#329 Use SET SESSION for schema modes
  schema/mysql/schema.sql
Labels: cla/signed

#299 Code quality
  cmd/icingadb/main.go
  internal/command/command.go
  pkg/com/bulker.go
  pkg/com/com.go
  pkg/com/counter.go
  pkg/com/entity_bulker.go
  pkg/config/config.go
  pkg/config/redis.go
  pkg/icingadb/db.go
  pkg/icingadb/delta.go
  pkg/icingadb/dump_signals.go
  pkg/icingadb/entitiesbyid.go
  pkg/icingadb/ha.go
  pkg/icingadb/objectpacker/objectpacker.go
  pkg/icingadb/sync.go
  pkg/icingadb/v1/history/meta.go
  pkg/icingadb/v1/meta.go
  pkg/icingaredis/client.go
  pkg/icingaredis/heartbeat.go
  pkg/icingaredis/utils.go
  pkg/icingaredis/v1/icinga_status.go
  pkg/icingaredis/v1/stats_message.go
  pkg/retry/retry.go
  pkg/types/acknowledgement_state.go
  pkg/types/binary.go
  pkg/types/bool.go
  pkg/types/comment_type.go
  pkg/types/notification_states.go
  pkg/types/notification_type.go
  pkg/types/notification_types.go
  pkg/types/state_type.go
  pkg/utils/utils.go
Labels: cla/signed

#323 Downtime: Add parent_id
  pkg/icingadb/v1/downtime.go
  pkg/icingadb/v1/history/downtime.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: enhancement, area/configsync, area/history, area/schema, cla/signed

#338 Support --version
  internal/command/command.go
  internal/version.go
  pkg/config/config.go
Labels: cla/signed

#343 Separate required and optional configuration for database and Redis
  pkg/config/database.go
  pkg/config/redis.go
  pkg/icingadb/db.go
  pkg/icingaredis/client.go
Labels: cla/signed
