Repository Icinga/icingadb, pull requests merged in 2021-09, with the labels that each got.

#358 Ensure extra config options are properly initialized
  pkg/config/config.go
  pkg/config/database.go
  pkg/config/redis.go
  pkg/icingadb/db.go
  pkg/icingaredis/client.go
Labels: bug, cla/signed

#301 Introduce downtime#scheduled_by
  pkg/icingadb/v1/downtime.go
  pkg/icingadb/v1/history/downtime.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: enhancement, area/configsync, area/schema, cla/signed

#345 Move etc/icingadb.service to packaging repositories
  etc/icingadb.service
Labels: enhancement, cla/signed

#348 Integration tests
  .github/workflows/integration-tests.yml
  tests/environment_test.go
  tests/go.mod
  tests/go.sum
  tests/history_test.go
  tests/instance_test.go
  tests/internal/utils/slice.go
  tests/internal/value/notification_states.go
  tests/internal/value/notification_types.go
  tests/internal/value/value.go
  tests/main_test.go
  tests/object_sync_test.conf
  tests/object_sync_test.go
  tests/state_sync_test.go
Labels: cla/signed, area/tests

#344 Schema: Add description to downtime columns 'triggered_by_id' and 'parent_id'
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: area/schema, cla/signed

#362 Update icinga-testing and use new features
  tests/environment_test.go
  tests/go.mod
  tests/go.sum
  tests/object_sync_test.go
Labels: enhancement, cla/signed, area/tests

#356 Clarify what MustPackAny() does
  pkg/icingadb/objectpacker/objectpacker.go
  pkg/icingadb/v1/customvar.go
Labels: cla/signed

#368 On shutdown: give up HA handover after 3s, not 5m
  cmd/icingadb/main.go
  pkg/icingadb/ha.go
Labels: cla/signed

#372 Fix use of wrong log function on heartbeat loss
  pkg/icingaredis/heartbeat.go
Labels: bug, cla/signed

#365 Fix data races
  pkg/com/counter.go
  pkg/contracts/contracts.go
  pkg/icingaredis/client.go
Labels: cla/signed

#361 Redis HYield: remove duplicates returned by HSCAN
  pkg/icingaredis/client.go
Labels: bug, area/configsync, cla/signed

#369 Log all different failed and recovered reconnects to backends
  pkg/config/redis.go
  pkg/driver/driver.go
  pkg/icingadb/db.go
  pkg/retry/retry.go
Labels: cla/signed

#373 Rewrite delta to use only a single goroutine
  go.mod
  pkg/icingadb/delta.go
  pkg/icingadb/delta_test.go
Labels: enhancement, cla/signed

#370 Include CheckResult#scheduling_source in state and history
  pkg/icingadb/v1/history/state.go
  pkg/icingadb/v1/state.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: cla/signed

#377 Remove example configuration from docs
  doc/03-Configuration.md
Labels: cla/signed

#374 Schema: s/mediumtext/longtext/
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
Labels: enhancement, area/schema, cla/signed

#366 Child loggers
  cmd/icingadb/main.go
  config.yml.example
  doc/03-Configuration.md
  internal/command/command.go
  internal/logging/logging.go
  pkg/config/config.go
  pkg/config/logging.go
Labels: cla/signed
