Repository Icinga/icingadb, pull requests merged in 2022-06, with the labels that each got.

#490 Fix `icingadb --version` output when using older Git versions
  pkg/version/version.go
Labels: cla/signed

#496 Docs: use @localhost instead of @127.0.0.1 for MySQL user
  doc/02-Installation.md
Labels: area/documentation, cla/signed

#493 Schema consistency for relations
  cmd/icingadb/main.go
  pkg/icingadb/v1/checkable.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
  schema/pgsql/schema.sql
  tests/object_sync_test.go
Labels: area/schema, cla/signed

#502 oneBulk(): terminate once input closed (like the regular bulker)
  pkg/com/bulker.go
Labels: bug, cla/signed

#501 Make Database/Redis schema mismatch error more user friendly
  cmd/icingadb/main.go
Labels: cla/signed

#464 Write own status into Redis
  cmd/icingadb/main.go
  config.example.yml
  doc/02-Installation.md
  doc/03-Configuration.md
  pkg/com/atomic.go
  pkg/driver/driver.go
  pkg/icingadb/cleanup.go
  pkg/icingadb/db.go
  pkg/icingadb/ha.go
  pkg/icingadb/history/retention.go
  pkg/icingadb/history/sync.go
  pkg/icingadb/overdue/sync.go
  pkg/icingadb/runtime_updates.go
  pkg/icingadb/sync.go
  pkg/icingaredis/client.go
  pkg/icingaredis/heartbeat.go
  pkg/icingaredis/telemetry/heartbeat.go
  pkg/icingaredis/telemetry/stats.go
Labels: enhancement, cla/signed

#499 Add environment_id to indices for history retention
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
  schema/pgsql/schema.sql
Labels: cla/signed

#497 Update example config and docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/version.yml
  CHANGELOG.md
  README.md
  RELEASE.md
  config.example.yml
  doc/01-About.md
  doc/02-Installation.md
  doc/02-Installation.md.d/01-Amazon-Linux.md
  doc/02-Installation.md.d/02-CentOS.md
  doc/02-Installation.md.d/03-Debian.md
  doc/02-Installation.md.d/04-RHEL.md
  doc/02-Installation.md.d/05-SLES.md
  doc/02-Installation.md.d/06-Ubuntu.md
  doc/03-Configuration.md
  doc/04-Upgrading.md
  doc/05-Distributed-Setups.md
  doc/images/about/icinga-db-in-icinga-context.png
  doc/images/icingadb-architecture.png
  doc/images/icingadb-daemon.png
  doc/images/icingadb-dashboard.png
  doc/images/icingadb-database.png
  doc/images/icingadb-envs.png
  doc/images/icingadb-ha.png
  doc/images/icingadb-web.png
  pkg/config/redis.go
Labels: area/documentation, cla/signed
