Repository Icinga/icingadb, pull requests merged in 2022-05, with the labels that each got.

#458 Support *nix sockets as documented
  doc/03-Configuration.md
  pkg/config/database.go
Labels: bug, area/documentation, area/connection, cla/signed

#467 Use Icinga DB docker instance for retention tests
  tests/cleanup_and_retention_test.go
  tests/go.mod
  tests/go.sum
Labels: cla/signed

#470 Update dependabot reviewers
  .github/dependabot.yml
Labels: cla/signed

#459 Ensure icingadb_instance#responsible=n
  pkg/icingadb/ha.go
Labels: cla/signed

#456 Schema: Make custom variable names case insensitive
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
  schema/pgsql/schema.sql
Labels: area/schema, cla/signed

#471 go:embed LUA script
  pkg/icingadb/overdue/get_overdues.lua
  pkg/icingadb/overdue/sync.go
Labels: cla/signed

#478 Don't print a stacktrace on config errors
  internal/command/command.go
Labels: cla/signed

#483 DB: use default ports and allow setting port for PostgreSQL Unix domain sockets
  pkg/config/database.go
Labels: area/connection, cla/signed

#480 Retention: periodically log number of items removed
  pkg/icingadb/history/retention.go
Labels: area/history, cla/signed

#481 Retention: remove leftover code from older tests
  pkg/icingadb/cleanup.go
  pkg/icingadb/history/retention.go
Labels: area/history, cla/signed

#477 Check for required database and Redis config options during config validation
  pkg/config/database.go
  pkg/config/redis.go
Labels: cla/signed

#461 PostgreSQL: Support LIKE for integer/enum columns
  schema/pgsql/schema.sql
Labels: enhancement, cla/signed

#474 Retention: take environment_id into account
  pkg/icingadb/cleanup.go
  pkg/icingadb/history/retention.go
  schema/pgsql/schema.sql
  tests/cleanup_and_retention_test.go
  tests/internal/utils/redis.go
Labels: cla/signed

#486 Integration tests: use separate artifact names for MySQL/PostgreSQL
  .github/workflows/integration-tests.yml
Labels: cla/signed, area/tests

#482 Add CommandArgument#Separator
  pkg/icingadb/db.go
  pkg/icingadb/v1/command.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
  schema/pgsql/schema.sql
Labels: cla/signed

#489 Streamline IsRetryable functions and retry DNS errors
  pkg/config/redis.go
  pkg/driver/driver.go
  pkg/retry/retry.go
Labels: cla/signed
