Repository Icinga/icingadb, pull requests merged in 2022-02, with the labels that each got.

#436 Fix currently not able to enable TLS
  pkg/config/config.go
  pkg/config/database.go
  pkg/config/redis.go
Labels: bug, area/connection, cla/signed

#420 Schema: make notification_history#text longtext
  cmd/icingadb/main.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
Labels: cla/signed

#440 Docs: don’t explain MySQL installation
  doc/02-Installation.md
Labels: area/documentation, cla/signed

#439 Add previous_soft_state to host_state and service_state
  pkg/icingadb/v1/state.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
Labels: cla/signed
