Repository Icinga/icingadb, pull requests merged in 2022-01, with the labels that each got.

#430 Update dependabot reviewers
  .github/dependabot.yml
Labels: cla/signed

#431 Run daily integration tests
  .github/workflows/integration-tests.yml
Labels: cla/signed, area/tests

#422 Integration tests: test that both icinga2 instances write identical history streams
  tests/go.mod
  tests/go.sum
  tests/history_test.go
Labels: area/history, cla/signed, area/tests

#423 GHA: go mod tidy
  .github/workflows/go.yml
Labels: cla/signed

#434 GHA: use latest staticcheck version
  .github/workflows/go.yml
Labels: cla/signed
