Repository Icinga/icingadb, pull requests merged in 2022-03, with the labels that each got.

#441 Fix typo
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
Labels: cla/signed

#446 doc: Document the password option for Redis
  doc/03-Configuration.md
Labels: cla/signed

#449 Fix intermittent test failures
  tests/go.mod
  tests/go.sum
  tests/history_test.go
Labels: cla/signed, area/tests

#221 Support PostgreSQL
  .github/workflows/compliance/anonymize-license.pl
  README.md
  cmd/icingadb/main.go
  config.yml.example
  doc/01-About.md
  doc/02-Installation.md
  doc/03-Configuration.md
  go.mod
  go.sum
  pkg/com/entity_bulker.go
  pkg/config/database.go
  pkg/driver/driver.go
  pkg/driver/pgsql.go
  pkg/icingadb/db.go
  pkg/icingadb/ha.go
  pkg/icingadb/runtime_updates.go
  pkg/types/string.go
  pkg/utils/utils.go
  schema/pgsql/schema.sql
Labels: enhancement, area/connection, needs-feedback, cla/signed

#418 Port integration tests to PostgreSQL
  .github/workflows/integration-tests.yml
  tests/environment_test.go
  tests/go.mod
  tests/go.sum
  tests/history_test.go
  tests/main_test.go
  tests/object_sync_test.go
  tests/regression_394_test.go
Labels: cla/signed

#435 History retention
  cmd/icingadb/main.go
  config.yml.example
  doc/03-Configuration.md
  pkg/config/config.go
  pkg/config/history_retention.go
  pkg/icingadb/cleanup.go
  pkg/icingadb/history/retention.go
  pkg/periodic/periodic.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0.sql
  tests/cleanup_and_retention_test.go
  tests/go.mod
  tests/go.sum
  tests/main_test.go
Labels: cla/signed
