Repository Icinga/icingadb, pull requests merged in 2023-08, with the labels that each got.

#617 schema: Add new index for `customvar_flat`
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.2.0.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.2.0.sql
Labels: cla/signed

#616 schema: Add missing indices to `hostgroup` and `servicegroup`
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.2.0.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.2.0.sql
Labels: cla/signed

#633 GitHub Actions: use actions/setup-go@v4 and go-version: 1.x
  .github/workflows/compliance.yml
  .github/workflows/go.yml
  .github/workflows/integration-tests.yml
  .github/workflows/sql.yml
  .github/workflows/version.yml
  pkg/icingadb/v1/environment.go
  pkg/utils/utils.go
  pkg/version/version.go
Labels: cla/signed

#626 Schema: change sort order of history event type enum
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.2.0.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.2.0.sql
Labels: area/schema, cla/signed

#630 Merge schema files and increase schema version for v1.1.1
  pkg/icingadb/db.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.1.1.sql
  schema/mysql/upgrades/1.2.0.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.1.1.sql
  schema/pgsql/upgrades/1.2.0.sql
Labels: cla/signed

#634 GitHub Actions: change master to main
  .github/workflows/compliance.yml
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration-tests.yml
  .github/workflows/sql.yml
  .github/workflows/version.yml
Labels: cla/signed

#629 Release 1.1.1
  AUTHORS
  CHANGELOG.md
  doc/04-Upgrading.md
  internal/version.go
Labels: cla/signed

#636 GitHub Actions: also run on support branches
  .github/workflows/compliance.yml
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration-tests.yml
  .github/workflows/sql.yml
  .github/workflows/version.yml
Labels: cla/signed

#637 doc/04-Upgrading.md: Fix path for schema upgrades
  doc/04-Upgrading.md
Labels: area/documentation, cla/signed

#638 doc/04-Upgrading.md: Fix path for schema upgrades
  doc/04-Upgrading.md
Labels: area/documentation, cla/signed

#640 GitHub Actions: remove version check
  .github/workflows/version.yml
Labels: cla/signed

#639 GitHub Actions: remove version check
  .github/workflows/version.yml
Labels: cla/signed
