Repository Icinga/icingadb, pull requests merged in 2023-07, with the labels that each got.

#619 Make integration tests work with Go 1.20.6
  tests/go.mod
  tests/go.sum
Labels: cla/signed, area/tests

#612 {Bool,Binary,UnixMilli}#MarshalJSON(): return valid JSON, not empty string
  pkg/types/binary.go
  pkg/types/binary_test.go
  pkg/types/bool.go
  pkg/types/bool_test.go
  pkg/types/unix_milli.go
  pkg/types/unix_milli_test.go
Labels: bug, cla/signed

#605 Config parsing: fail on unknown fields and print them
  cmd/icingadb-migrate/main.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: cla/signed

#601 Write a hint for empty arrays/dicts into `customvar_flat`
  pkg/flatten/flatten.go
  pkg/icingadb/v1/customvar.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.2.0.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.2.0.sql
  tests/object_sync_test.go
Labels: bug, area/configsync, cla/signed, area/runtime

#551 icingadb-migrate: handle NULL event time columns
  cmd/icingadb-migrate/convert.go
Labels: cla/signed

#593 Merge network and database error retryability detection functions
  pkg/icingadb/db.go
  pkg/icingadb/ha.go
  pkg/retry/retry.go
Labels: cla/signed

#623 cmd/icingadb-migrate: ignore icinga_downtimehistory#was_started=0 rows
  cmd/icingadb-migrate/convert.go
  cmd/icingadb-migrate/embed/downtime_query.sql
Labels: bug, cla/signed

#609 Support Percona XtraDB Cluster by not using SERIALIZABLE transactions directly
  pkg/icingadb/ha.go
Labels: cla/signed

#554 convertFlappingRows(): fix foreign key error history -> flapping_history
  cmd/icingadb-migrate/convert.go
  cmd/icingadb-migrate/main.go
  cmd/icingadb-migrate/misc.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cla/signed
