Repository Icinga/icingadb, pull requests merged in 2024-03, with the labels that each got.

#690 cmd/icingadb: Log Icinga DB version during startup
  cmd/icingadb/main.go
Labels: cla/signed

#694 docs: Fix link to `Icinga DB Web`
  doc/03-Configuration.md
Labels: cla/signed

#696 tests/go.mod: bump github.com/icinga/icinga-testing "version"
  tests/go.mod
  tests/go.sum
Labels: cla/signed

#695 Update dependabot config
  .github/dependabot.yml
Labels: dependencies, cla/signed

#709 Integration tests: don't hard-code MySQL in some tests
  tests/history_bench_test.go
  tests/history_test.go
  tests/sla_test.go
Labels: cla/signed

#693 Retry broken pipe errors (`EPIPE`)
  pkg/retry/retry.go
Labels: bug, cla/signed

#699 MySQL/MariaDB: Use strict SQL mode
  pkg/config/database.go
Labels: cla/signed

#684 Remove redundant closure
  pkg/driver/driver.go
Labels: enhancement, area/connection, cla/signed

#710 PostgreSQL: get_sla_ok_percent to return decimal
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.1.2.sql
  tests/sql/sla_test.go
Labels: cla/signed

#700 MySQL/MariaDB: Fix `icingadb_schema.timestamp` not being UNX time
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.0.0-rc2.sql
  schema/mysql/upgrades/1.0.0.sql
  schema/mysql/upgrades/1.1.1.sql
  schema/mysql/upgrades/1.1.2.sql
Labels: cla/signed

#715 Upgrade `go-redis` to `v9`
  cmd/icingadb/main.go
  go.mod
  go.sum
  pkg/config/redis.go
  pkg/icingadb/dump_signals.go
  pkg/icingadb/history/sla.go
  pkg/icingadb/history/sync.go
  pkg/icingadb/overdue/sync.go
  pkg/icingadb/runtime_updates.go
  pkg/icingaredis/client.go
  pkg/icingaredis/heartbeat.go
  pkg/icingaredis/telemetry/heartbeat.go
  pkg/icingaredis/telemetry/stats.go
  pkg/icingaredis/utils.go
  tests/go.mod
  tests/go.sum
  tests/history_bench_test.go
  tests/history_test.go
  tests/internal/utils/redis.go
  tests/object_sync_test.go
Labels: cla/signed

#657 Flatten(): render even large numbers as-is, not using scientific notation
  cmd/icingadb-migrate/convert.go
  pkg/flatten/flatten.go
  pkg/flatten/flatten_test.go
  pkg/icingadb/ha.go
  pkg/types/string.go
Labels: bug, area/configsync, cla/signed

#718 Document `retention.count` & `retention.interval` options
  config.example.yml
  doc/03-Configuration.md
Labels: area/documentation, enhancement, cla/signed

#723 Document `database.options` properly
  config.example.yml
  doc/03-Configuration.md
Labels: area/documentation, enhancement, cla/signed
