Repository Icinga/icingadb, pull requests merged in 2024-10, with the labels that each got.

#805 Shorten CommentType#UnmarshalText()
  pkg/icingadb/types/comment_type.go
Labels: cla/signed

#819 pkg/icingaredis/: check context termination while looping over channel
  pkg/icingaredis/utils.go
Labels: cla/signed

#824 RetentionConfig: restrict days to uint16
  internal/config/config.go
  pkg/icingadb/history/retention.go
Labels: cla/signed

#821 Introduce golangci-lint and fix findings
  .github/workflows/go.yml
  cmd/icingadb-migrate/convert.go
  cmd/icingadb-migrate/main.go
  cmd/icingadb-migrate/misc.go
  cmd/icingadb/main.go
  pkg/icingadb/cleanup.go
  pkg/icingadb/delta_test.go
  pkg/icingadb/types/notification_type.go
Labels: enhancement, cla/signed, github_actions

#797 Make structifyStream() channel types more explicit, e.g. input only
  pkg/icingadb/runtime_updates.go
Labels: enhancement, cla/signed

#812 Use `sync/atomic#Pointer` instead of our own wrapper
  cmd/icingadb/main.go
  pkg/icingadb/ha.go
  pkg/icingaredis/telemetry/heartbeat.go
Labels: enhancement, cla/signed

#829 Replace `int64` with `atomic.Int64` where applicable
  cmd/icingadb/main.go
  pkg/icingaredis/heartbeat.go
  pkg/icingaredis/telemetry/heartbeat.go
Labels: enhancement

#823 Adjust installation docs for centralized icinga.com doc injection
  doc/02-Installation.md
  doc/02-Installation.md.d/01-Amazon-Linux.md
  doc/02-Installation.md.d/02-CentOS.md
  doc/02-Installation.md.d/03-Debian.md
  doc/02-Installation.md.d/04-RHEL.md
  doc/02-Installation.md.d/05-SLES.md
  doc/02-Installation.md.d/06-Ubuntu.md
  doc/02-Installation.md.d/From-Source.md
  doc/03-Configuration.md
Labels: area/documentation, enhancement, cla/signed
