Repository Icinga/icingadb, pull requests merged in 2024-07, with the labels that each got.

#769 cmd/icingadb-migrate: replace magic number 20 with sha1.Size
  cmd/icingadb-migrate/main.go
Labels: bug, cla/signed

#768 icingadb-migrate: Verify env ID length
  cmd/icingadb-migrate/main.go
Labels: enhancement, cla/signed

#760 doc/02-Installation.md: Fix installing-icingadb-db-packages anchor
  doc/02-Installation.md
Labels: area/documentation, cla/signed

#767 icingadb-migrate: Mitigate NULL names in {comment,downtime}_query
  cmd/icingadb-migrate/embed/comment_query.sql
  cmd/icingadb-migrate/embed/downtime_query.sql
Labels: bug, crash, cla/signed
