Repository Icinga/icingadb, pull requests merged in 2024-09, with the labels that each got.

#737 Docs: Fix whitespaces
  doc/02-Installation.md
  doc/02-Installation.md.d/01-Amazon-Linux.md
  doc/02-Installation.md.d/02-CentOS.md
  doc/02-Installation.md.d/03-Debian.md
  doc/02-Installation.md.d/04-RHEL.md
  doc/02-Installation.md.d/05-SLES.md
  doc/02-Installation.md.d/06-Ubuntu.md
  doc/03-Configuration.md
  doc/06-Migration.md
Labels: area/documentation, cla/signed

#808 Test history.*Downtime*Time#Value()
  pkg/icingadb/v1/history/downtime_test.go
Labels: cla/signed, area/tests

#807 Test history.FlappingEventTime#Value()
  pkg/icingadb/v1/history/flapping_test.go
Labels: cla/signed, area/tests

#806 Test Environment
  pkg/icingadb/v1/environment_test.go
Labels: cla/signed, area/tests

#801 Shorten icingadb/v1.AddressBin#Value()
  pkg/icingadb/v1/host.go
Labels: cla/signed

#813 Update GHA dependencies via dependabot
  .github/dependabot.yml
Labels: cla/signed

#809 GHA: Remove -gcflags="-m" from go build
  .github/workflows/go.yml
Labels: cla/signed
