Repository Icinga/icingadb, pull requests merged in 2024-12, with the labels that each got.

#859 Fix typo
  cmd/icingadb/main.go
Labels: cla/signed

#856 schema: Fix broken upgrade script `1.3.0`
  schema/mysql/upgrades/1.3.0.sql
Labels: bug, area/schema, cla/signed

#800 Abort HA Realization Logic After Timeout
  cmd/icingadb/main.go
  pkg/icingadb/ha.go
  pkg/icingaredis/heartbeat.go
Labels: bug, cla/signed

#825 HA State: ensure not this and another instance can be responsible
  pkg/icingadb/ha.go
Labels: bug, ref/IP, cla/signed

#876 test: Rebind Log Output Query for PostgreSQL
  tests/history_test.go
Labels: bug, cla/signed, area/tests

#874 Docs: Redis ACL Username and Database
  config.example.yml
  doc/03-Configuration.md
Labels: area/documentation, cla/signed

#828 HA: Limit max open database connections to `1`
  cmd/icingadb/main.go
Labels: bug, cla/signed

#871 Release Icinga DB Version 1.2.1
  .mailmap
  AUTHORS
  CHANGELOG.md
  doc/04-Upgrading.md
  internal/version.go
  schema/mysql/upgrades/1.2.1.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.2.1.sql
Labels: cla/signed
