Repository Icinga/icingadb, pull requests merged in 2024-04, with the labels that each got.

#725 `history.Sync`: Don't operate on closed channel
  pkg/icingadb/history/sync.go
Labels: bug, area/history, cla/signed

#692 Enhance HA "Taking over", "Handing over" logging
  cmd/icingadb/main.go
  pkg/icingadb/ha.go
  pkg/icingaredis/heartbeat.go
Labels: cla/signed

#711 Try setting `wsrep_sync_wait` for mysql connections
  cmd/icingadb-migrate/misc.go
  config.example.yml
  doc/03-Configuration.md
  pkg/config/database.go
  pkg/driver/driver.go
  pkg/driver/pgsql.go
  pkg/icingadb/cleanup.go
  pkg/icingadb/db.go
  pkg/icingadb/driver.go
  pkg/icingadb/ha.go
Labels: cla/signed

#656 Unify check attempt data type to uint32 already used somewhere
  cmd/icingadb-migrate/convert.go
  doc/04-Upgrading.md
  pkg/icingadb/db.go
  pkg/icingadb/v1/checkable.go
  pkg/icingadb/v1/history/state.go
  pkg/icingadb/v1/state.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.1.2.sql
  schema/mysql/upgrades/optional/1.1.2-history.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.1.2.sql
  schema/pgsql/upgrades/optional/1.1.2-history.sql
Labels: ref/IP, cla/signed, consider backporting

#732 Register mysql default logger prior to `mysql#NewConfig()`
  pkg/config/database.go
Labels: bug, cla/signed

#733 Remove deprecated io/ioutil package references
  pkg/config/config.go
  pkg/icingadb/objectpacker/objectpacker.go
  tests/history_test.go
Labels: cla/signed

#739 Retry `io.EOF` error
  pkg/retry/retry.go
Labels: bug, cla/signed

#741 icingadb: Remove shouldRetry
  pkg/icingadb/driver.go
Labels: cla/signed

#740 icingadb.DB: Retry Schema Checks
  pkg/icingadb/db.go
Labels: bug, cla/signed

#736 Account Redis' trademark policy
  README.md
  config.example.yml
  doc/01-About.md
  doc/02-Installation.md
  doc/03-Configuration.md
  doc/04-Upgrading.md
  doc/05-Distributed-Setups.md
  doc/TRADEMARKS.md
  doc/images/icingadb-architecture.png
  doc/images/icingadb-daemon.png
  doc/images/icingadb-database.png
  doc/images/icingadb-envs.png
  doc/images/icingadb-ha.png
  doc/images/icingadb-web.png
Labels: area/documentation, cla/signed

#738 Unify notation of `n * time.Duration`
  pkg/backoff/backoff.go
  pkg/icingadb/driver.go
  pkg/icingadb/ha.go
  pkg/icingaredis/heartbeat.go
Labels: cla/signed
