Repository Icinga/icingadb, pull requests merged in 2025-05, with the labels that each got.

#950 Doc: Big Picture Overview, Forced Logs, Operations
  doc/01-About.md
  doc/03-Configuration.md
  doc/07-Operations.md
Labels: area/documentation, cla/signed

#804 Test icingadb.EntitiesById
  pkg/icingadb/entitiesbyid_test.go
Labels: cla/signed, area/tests

#944 Small Logging Rework: More logging in OnRetryableError in HA.realize and abort with a message instead of a stack trace
  cmd/icingadb/main.go
  pkg/icingadb/ha.go
Labels: cla/signed

#957 icingadb-migrate: Logger for Database connections
  cmd/icingadb-migrate/main.go
Labels: cla/signed

#961 Retention: Unordered deletion in CleanupStmt
  pkg/icingadb/cleanup.go
  pkg/icingadb/history/retention.go
Labels: cla/signed
