Repository Icinga/icingadb, pull requests merged in 2025-06, with the labels that each got.

#963 Add icingadb_version column to icingadb_instance
  pkg/icingadb/ha.go
  pkg/icingadb/v1/icingadb_instance.go
  schema/mysql/schema.sql
  schema/mysql/upgrades/1.4.0.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/1.4.0.sql
Labels: enhancement, area/ha, cla/signed

#970 pkg/icingadb: Use backoff.DefaultBackoff
  pkg/icingadb/cleanup.go
  pkg/icingadb/ha.go
  pkg/icingadb/schema.go
Labels: cla/signed

#942 docs/04-Upgrading.md: Database Schema Upgrades
  doc/04-Upgrading.md
Labels: area/documentation, cla/signed

#981 Add a Redis tuning note about huge setups
  doc/07-Operations.md
Labels: area/documentation, cla/signed

#983 docs: Mention icingadb-selinux package
  doc/02-Installation.md
Labels: area/documentation, cla/signed
